title: José María Reyes Retana Tamayo
logo: Recursos HitHub io/Foto_Perfil_2025.jpeg
description: Bienvenido a mi portafolio de análisis de datos.\n He seleccionado el proyecto que realicé sobre un análisis utilizado para poder determinar la eficiencia de los empleados de un Call-Center.
show_downloads: false

theme: jekyll-theme-minimal
