title: Mariel González Martínez
logo: Recursos HitHub io/Foto_Perfil_2025.jpeg
description: Bienvenido a mi portafolio de análisis de datos.
show_downloads: false
#google_analytics:
theme: jekyll-theme-minimal
